version: '3.7'
services:
  backend:
    container_name: kapulus-backend
    build:
      context: ../kapulus-backend
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - ../kapulus-backend:/usr/src/app/kapulus-backend
      - /usr/src/app/kapulus-backend/node_modules
    ports:
      - '5000:5000'
networks:
      default:        
          name: kapulus-network