version: '3.7'
services:
  backend:
    container_name: kapulus-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '5000:4000'
networks:
      default:        
          name: kapulus-network